### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ralls0** [polito-pds-project/calendar-todo-list-cpp#12]
- [x] Unire la classe astratta `ClientCalendar` e `ClientCalendar_CalDAV`.
- [x] Gestire in modo corretto lo stato del calendario.
- [ ] Creare la documentazione a riguardo delle signal, indicandone la forma e quando vengono emesse.
- [x] Strutturare in modo più omogeneo e consono il CalendarManager.
- [x] Proteggere l'accesso agli eventi con cv e unique_lock.
